### ISSUE TITLE
User Model

### ISSUE THREAD

**Issue by NathanBland** [whiteboards/habitus-API#2]
``` javascript
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
// import { belongsTo, hasMany } from 'ember-data/relationships';

export default Model.extend({
  firstName: attr('string'),
  lastName: attr('string'),
  email: attr('string'),
  displayName: attr('string'),
  password: attr('string')  
});
```

Preliminary user model. Subject to changes and such.

**Comment by NathanBland** [comment]
This should probably also have a token as a string... so you can see what token a user is currently using, and revoke it if needed.

**Comment by crodeheaver** [comment]
Mmmmm..... ok. Sure. I should be able to store the current token. Probably...

**Comment by NathanBland** [comment]
You aren't going to like me..

Please add this prop to the user model

``` javascript
role: attr('string'),
```

**Comment by crodeheaver** [comment]
No. Too late.

**Comment by NathanBland** [comment]
Please? :shipit:

**Comment by crodeheaver** [comment]
Ok...

**Comment by NathanBland** [comment]
awesome! :100: :+1: :fireworks: :tada:
