### ISSUE TITLE
Merge to habitus branches.

### ISSUE THREAD

**Issue by NathanBland** [whiteboards/habitus-API#5]
We really should get around to merging both of the branches for this into one.. 
To do this a couple of things need to happen:
- [ ] current state pushed up to both repositories
- [ ] build scripts for each clearly documented
- [ ] remove old `.git` from the repository being merged in
- [ ] combine `.gitignore` files so we don't end up with trash in the repository

There are probably a few other things, but that is what comes to mind off hand.

**Comment by crodeheaver** [comment]
Looks like we can check this one off.
